language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pygame
  - pip install unittest
# command to run tests
script:
  - coverage run the_game/backend/test_snake_model.py
